name: Update Scholar Data

on: 
    schedule:
        - cron '0 2 * * 0'
    workflow_dispatch:
    push:
        paths:
            - 'sctripts/parse_scholar.py'
            - '.github/workflows/scholar.yml'


jobs: 
    update-publications:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            
            - name: Install pip dependencies
              run: |
                python -m pip install --upgrade pip
                pip install scholarly
            
            - name: Run scholar parsing script
              run: |
                cd scripts
                python parse_scholar.py
            
            - name: Commit and push changes
              run: |
                git config --local user.name "GitHub Actions"
                git config --local user.email "action@github.com"
                git add scripts/publications.json
                if git diff --staged --quiet; then
                    echo "No changes to commit."
                else
                    git commit -m "Update publications data"
                    git push origin main
                fi